### ISSUE TITLE
Not able to add repository to HACS

### ISSUE THREAD

**Issue by pshrm** [nechry/elco-remocon-net-appdaemon#20]
When I try to add nechry/elco-remocon-net-appdaemon in the custom repository in HACS I get following error
No manifest.json file found 'manifest.json'

**Comment by nechry** [comment]
you don't have to add the repo, the appdaemon is already available in HACS

**Comment by pshrm** [comment]
As per readme, I would need it for “Installing AppDaemon Backend Application” or no?

**Comment by nechry** [comment]
yes definitively, is a prerequisite to load elco-remocon-net-appdaemon.
In order:
- HA AppDaemon (from Home Assistant's Supervisor Add-on Store)
- Install HACS,
- and at last elco-remocon-net-appdaemon from HACS.
You will have unfortunatly to manualy move what HACS install inside of HA Config, as AppDaemon have now an outside config folder
https://github.com/nechry/elco-remocon-net-appdaemon?tab=readme-ov-file#%EF%B8%8F-hacs-didnt-yet-install-the-addons-in-addon_configs-folder

**Comment by pshrm** [comment]
It worked! Thank you so much for wonderful work.
