### ISSUE TITLE
No manifest.json

### ISSUE THREAD

**Issue by f-engel-hrs** [nechry/elco-remocon-net-appdaemon#4]
Hey,

When trying to add your repository as custom integration via HACS, it complains that no manifest.json is provided.
Can you add one please? :)

**Comment by f-engel-hrs** [comment]
Nope just figured out how to actually get it to work. Missed the step to enable AppDeamon integration in HACS ans then add the repo.

**Comment by nechry** [comment]
@f-engel-hrs by the way you don't have to add it as custom repo. You can directly find it on default HACS repo
