### ISSUE TITLE
Error fetching data

### ISSUE THREAD

**Issue by michael-bang** [nechry/elco-remocon-net-appdaemon#9]
Thanks for creating the plugin !

I have just setup an Elco THISION MINI 15.3 gas system for heating rooms and water in my house. 
I have registered at the https://www.remocon-net.remotethermo.com/ homepage and can see my equipment and stats through the homepage and app.

I have configured your plugin and it seems that the plugin is able to login, but when it try to fetch the data I get a html page back with:

---
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ERROR - Remocon NET</title>
    <link rel="shortcut icon" type="image/ico" href="/Content/images/favicon-elco.ico?ver=15151">
    <link href="https://www.remocon-net.remotethermo.com:443/Content/R2/css/elco.min.css" rel="stylesheet"/>

</head>
<body class="bg-default">
<nav class="navbar fixed-top bg-navbar justify-content-between">
    <div class="d-flex justify-content-center">
        <a class="navbar-brand ms-3 me-auto d-flex align-items-center" href="/R2/Home">
            <div class="gfm-image--brand" alt=""></div>
        </a>
    </div>
</nav>

<div class="container-lg container-fluid p-3">
    <div class="row justify-content-center">
        <div class="col col-lg-8">
            <div class="card">
                <div class="card-body gy-2">
                    <div class="gfm-tf-h2 mb-2">AN ERROR OCCURRED PROCESSING YOUR REQUEST</div>
                    <div class="row mb-2">
                        <div class="col">
                            Please report the following error to the system administrator
                        </div>
                    </div>
                    <div class="row mb-2 mb-sm-0">
                        <div class="col-sm-6">
                            ERROR TYPE:
                        </div>
                        <div class="col-sm-6">
                            UtilsLib.Diagnostics.ViolatedPreConditionException
                        </div>
                    </div>
                        <div class="row">
                            <div class="col-sm-6">
                                ERROR MESSAGE:
                            </div>
                            <div class="col-sm-6">
                                Violated Precondition (CheckId: 160902105616)
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

---

Any idea what I should look for ?

**Comment by michael-bang** [comment]
I had a look into what API the web GUI used in order to show data about my setup and I have now successfully made a script that can get the data for me.

**Comment by nechry** [comment]
Hello Michael, can you share your adaptations, maybe it is possible to do some configurations and support your boiler model

**Comment by michael-bang** [comment]
Hello Jean-François,

Yes, definitely and I hope you can use it.

I'm not an expert in Python so I had some problems searching through the
list of objects returned in the way you have done it. So this part could
definitely be done better :-) Any feedback on this would be greatly
appreciated.
I'm still in the process of figuring out if there is more information
provided in the response that I want to use in Home Assistant.

import hassapi as hass
import requests
import json
from urllib.parse import quote, urljoin
import posixpath


class Remocon(hass.Hass):
    def initialize(self):
        refresh_rate = self.args.get("refresh_rate")
        if refresh_rate is None:
            refresh_rate = 60
        self.log(f"Will fetch remocon.net data every {refresh_rate} min")
        self.run_every(self.get_remocon_data, "now", refresh_rate * 60)

    def post_to_entities(self, data):
        self.log("Posting to entities...")

        def _post_data(sensor, payload):
            try:
                # elco_sensor = self.get_entity(sensor)
                # if elco_sensor is None:
                entity_url = f"{ha_url}/api/states/{sensor}"
                token = "Bearer {}".format(self.args["bearer_token"])
                headers = {"Authorization": token, "Content-Type":
"application/json"}
                result = requests.post(entity_url, json=payload,
headers=headers)
                self.log(f"Set state on entity {sensor}")
                # else:
                #     elco_sensor.set_state(state = payload["state"],
attributes = payload["attributes"])
                #     self.log(f"update state of {sensor}")

            except Exception as e:
                self.log(e)

        def _post_plantData(plantData):
            outsideTemp =next(item for item in plantData if item["id"] ==
"OutsideTemp")
            data = {
                "state": outsideTemp["value"],
                "attributes": {
                    "unit_of_measurement": "°C",
                    "device_class": "temperature",
                    "friendly_name": "Elco Outside Temperature",
                },
            }
            _post_data("sensor.elco_outside_temperature", data)

            dhwStorageTemp=next(item for item in plantData if item["id"] ==
"DhwStorageTemperature")
            data = {
                "state": dhwStorageTemp["value"],
                "attributes": {
                    "unit_of_measurement": "°C",
                    "device_class": "temperature",
                    "friendly_name": "Elco Domestic Hot Water Storage
Temperature",
                },
            }
            _post_data(
                "sensor.elco_domestic_hot_water_storage_temperature",
                data,
            )


            dhwHeatCircuitPressure=next(item for item in plantData if
item["id"] == "HeatingCircuitPressure")
            data = {

                "state": dhwHeatCircuitPressure["value"],

                "attributes": {

                    "unit_of_measurement": "bar",

                    "device_class": "pressure",

                    "friendly_name": "Elco Domestic Boiler Pressure",

                },

            }

            _post_data(

                "sensor.elco_domestic_boiler_pressure",

                data,

            )

            dhwTemp=next(item for item in plantData if item["id"] ==
"DhwTemp")
            elco_domestic_hot_water_temperature = {
                "state": dhwTemp["value"],
                "attributes": {
                    "unit_of_measurement": "°C",
                    "device_class": "temperature",
                    "min": dhwTemp["min"],
                    "max": dhwTemp["max"],
                    "step": dhwTemp["step"],
                    "friendly_name": "Elco Domestic Hot Water Storage
Temperature Desired",
                },
            }
            _post_data(
                "sensor.elco_domestic_hot_water_temperature",
                elco_domestic_hot_water_temperature,
            )

            dhwMode=next(item for item in plantData if item["id"] ==
"DhwMode")
            data = {
                "state": "on" if dhwMode["value"] == 2 else "off",
                "attributes": {
                    "device_class": "running",
                    "friendly_name": "Elco Domestic Hot Water Storage Mode",
                    "icon": "mdi:hvac",
                },
            }
            _post_data(
                "binary_sensor.elco_domestic_hot_water_storage_mode",
                data,
            )

        def _post_zoneData(zoneData):
            desiredTemp=next(item for item in zoneData if item["id"] ==
"ZoneDesiredTemp")
            data = {
                "state": desiredTemp["value"],
                "attributes": {
                    "unit_of_measurement": "°C",
                    "device_class": "temperature",
                    "friendly_name": "Elco Desired Room Temperature",
                },
            }
            _post_data("sensor.elco_desired_room_temperature", data)

            zoneMode=next(item for item in zoneData if item["id"] ==
"ZoneMode")
            mode_dict = {0: "Protection", 1: "Automatic", 2: "Reduced", 3:
"Comfort"}
            data = {
                "state": mode_dict.get(zoneMode["value"]),
                "attributes": {
                    "icon": "mdi:radiator",
                    "friendly_name": "Elco Room Operation mode heating",
                },
            }
            _post_data(
                "sensor.elco_room_operation_mode_heating",
                data,
            )

        try:
            if self.args.get("ha_url"):
                # get HA's url from app's first, if configured/overridden
by user
                self.log("Using ha_url from app's configuration")
                ha_url = self.args["ha_url"]
            else:
                self.log("Using ha_url from plugins's HASS configuration")
                ha_url = self.config["plugins"]["HASS"]["ha_url"]
        except Exception as e:
            self.error(
                "No Home Assistant URL could be found. Please configure
ha_url in the app's configuration. Aborting."
            )
            self.error(e)
            return
        tempData = data["items"]
        for item in tempData:
            _post_plantData(tempData)
            _post_zoneData(tempData)

    def get_remocon_data(self, kwargs):
        self.log("Fetching remocon data...")
        try:
            base_url = self.args.get("base_url")
            if base_url is None:
                base_url = "https://www.remocon-net.remotethermo.com"
            zone = self.args.get("zone")
            if zone is None:
                zone = 1
            gateway = self.args.get("gateway_id")
            if not gateway:
                self.error(
                    "There was a problem getting configuration values,
gateway_id is not defined. Aborting."
                )
                return
            username = quote(self.args.get("username"), safe="")
            password = quote(self.args.get("password"), safe="")
        except Exception:
            self.error("There was a problem getting configuration values.
Aborting.")
            return
        try:
            login_url = urljoin(base_url,
"R2/Account/Login?returnUrl=HTTP/2")
            self.log("login_url")
            self.log(login_url)
            payload =
f"Email={username}&Password={password}&RememberMe=false"
            headers = {
                "Content-Type": "application/x-www-form-urlencoded",
                "Cookie": "browserUtcOffset=-120",
            }
            session = requests.session()
            # login, get session cookie and address for json data
            response = session.post(url=login_url, headers=headers,
data=payload)
            self.log(response)
            if response.status_code == 200:
                result_json = json.loads(response.text)
                if result_json["ok"]:
                    # get zone data
                    payload = {
                        "features": {
                            "gatewayId":gateway,

"zones":[{"num":1,"name":"","roomSens":False,"geofenceDeroga":False,"virtInfo":{"heatReqMode":1,"thermoregModeHeat":3,"thermoregModeCool":0,"undef":False},"isHidden":False},{"num":2,"name":"","roomSens":False,"geofenceDeroga":False,"virtInfo":{"heatReqMode":1,"thermoregModeHeat":1,"thermoregModeCool":0,"undef":False},"isHidden":True},{"num":3,"name":"","roomSens":False,"geofenceDeroga":False,"virtInfo":{"heatReqMode":1,"thermoregModeHeat":1,"thermoregModeCool":0,"undef":False},"isHidden":True}],
                            "solar":False,
                            "convBoiler":False,
                            "hpSys":False,
                            "hybridSys":False,
                            "cascadeSys":False,
                            "virtualZones":True,
                            "hasVmc":False,
                            "extendedTimeProg":False,
                            "hasBoiler":True,
                            "commBoiler":False,
                            "pilotSupported":False,
                            "isVmcR2":False,
                            "isEvo2":False,
                            "dhwProgSupported":True,
                            "dhwHidden":False,
                            "dhwBoilerPresent":True,
                            "dhwModeChangeable":True,
                            "hvInputOff":False,
                            "autoThermoReg":True,
                            "hasMetering":True,
                            "weatherProvider":0,
                            "hasFireplace":False,
                            "hasSlp":False,
                            "hasEm20":False,
                            "hasTwoCoolingTemp":False,
                            "bmsActive":False,
                            "hpCascadeSys":False,
                            "hpCascadeConfig":-1,
                            "bufferTimeProgAvailable":False,
                            "distinctHeatCoolSetpoints":False,
                            "hasZoneNames":False,
                            "hasGahp":False,
                            "hydraulicScheme":-1,
                            "preHeatingSupported":False,
                            "zigbeeActive":False,
                            "hasSlpAloneOnBus":False,
                            "isSlpCascade":False,
                            "hasDhwTimeProgTemperatures":2,
                            "hasZeroColdWaterProg":False},
                        "filter":{
                            "notEssentials":False,
                            "plant":True,
                            "zone":True,
                            "dhw":True
                            },
                        "useCache":True,
                        "zone":1
                    }
                    data_url = urljoin(
                        base_url, posixpath.join("R2/PlantHome/GetData",
gateway)
                    )
                    self.log(data_url)
                    response = session.post(url=data_url, json=payload)
                    if response.status_code == 200:
                        result_json = json.loads(response.text)
                        self.post_to_entities(result_json["data"])
                        self.log("Done fetching remocon data.")
                    else:
                        error_message = response.text
                        self.error(f"Fetching error: {error_message}")
                else:
                    error_message = result_json["message"]
                    self.error(f"Authentication failed: {error_message}")
            else:
                error_message = response.text
                self.error(f"Authentication error: {error_message}")
        except Exception as e:
            self.error(f"Unhandled exception: {e}")
